version: "2"

services:
  bot:
    container_name: road-dicobot
    build:
      context: .
    ports:
      - "15001:15001"
      - "15002:15002"
      - "15003:15003"
      - "15004:22"
    volumes:
      - ./:/home/road/ws
    restart: always


